#!/usr/bin/env bash
set -euo pipefail

slug="${CMUX_FEATURE_SLUG:-?}"
echo "[post-create] setting up worktree ${slug}"

MAIN="${CMUX_MAIN_WORKTREE:-}"
if [[ -z "${MAIN}" ]]; then
  echo "[post-create] CMUX_MAIN_WORKTREE is unset; cannot locate sibling files" >&2
  exit 1
fi

for name in ca.pem ca.key; do
  [[ -e "${MAIN}/${name}" ]] || continue
  [[ -e "${name}" || -L "${name}" ]] && continue
  ln -s "../../${name}" "${name}"
  echo "[post-create] linked ${name}"
done

# Generate a per-workspace compose override so parallel worktrees don't
# collide on host-published ports. cmux assigns each workspace a unique
# CMUX_PORT; we fan the stack's exposed ports out from that base. Only the
# host side of each mapping moves — internal container ports are unchanged.
if [[ -n "${CMUX_PORT:-}" && -f compose.yaml ]]; then
  base="${CMUX_PORT}"
  cat > compose.override.yaml <<EOF
# Generated by .cmux/post-create.sh for cmux workspace "${slug}" (CMUX_PORT=${base}).
# Remaps host-published ports off CMUX_PORT so parallel worktrees don't
# collide. Internal service-to-service ports are unchanged. Gitignored and
# regenerated per workspace — do not edit by hand.
services:
  frontend:
    ports: !override
      - "${base}:3000"
  temporal:
    ports: !override
      - "$((base + 1)):7233"
      - "$((base + 2)):8233"
  backend:
    ports: !override
      - "$((base + 3)):8000"
  moto:
    ports: !override
      - "$((base + 4)):5000"
EOF
  echo "[post-create] wrote compose.override.yaml (webui=${base}, temporal grpc=$((base + 1)), temporal ui=$((base + 2)), backend=$((base + 3)), moto=$((base + 4)))"
else
  echo "[post-create] CMUX_PORT unset or compose.yaml missing; skipping compose.override.yaml"
fi

if [[ -f frontend/package.json ]]; then
  if command -v pnpm >/dev/null 2>&1; then
    echo "[post-create] installing frontend deps"
    pnpm -C frontend install --frozen-lockfile
  else
    echo "[post-create] warning: pnpm not on PATH; skipping frontend install"
  fi
fi

echo "[post-create] done"
