.DEFAULT_GOAL := dev

# Canonical environment. Required for deploy targets, baseline for dev.
# Optional: missing .env is not an error.
ifneq (,$(wildcard .env))
include .env
export
endif

# Local dev overlay: only loaded for dev/test targets so deploy
# targets see only `.env`. Sequential include → later assignments win.
DEV_TARGETS := dev backend worker frontend app-up app-down app-logs \
               infra-up infra-down infra-logs test check
GOALS := $(or $(MAKECMDGOALS),$(.DEFAULT_GOAL))
ifneq (,$(filter $(DEV_TARGETS),$(GOALS)))
ifneq (,$(wildcard .env.local))
include .env.local
export
endif
endif

# Casper / cmux worktree port isolation. compose.override.yaml (auto-merged
# by docker compose, gitignored) may remap the published host ports so
# parallel workspaces don't collide. When present it is the source of truth:
# read the actual published ports from it so the endpoint banner and the
# host-side `make dev` flow never diverge from what docker binds. Otherwise
# fall back to the conventional defaults.
ifneq (,$(wildcard compose.override.yaml))
FRONTEND_PORT      := $(shell sed -nE 's/.*"([0-9]+):3000".*/\1/p' compose.override.yaml | head -n1)
TEMPORAL_GRPC_PORT := $(shell sed -nE 's/.*"([0-9]+):7233".*/\1/p' compose.override.yaml | head -n1)
TEMPORAL_UI_PORT   := $(shell sed -nE 's/.*"([0-9]+):8233".*/\1/p' compose.override.yaml | head -n1)
BACKEND_PORT       := $(shell sed -nE 's/.*"([0-9]+):8000".*/\1/p' compose.override.yaml | head -n1)
MOTO_PORT          := $(shell sed -nE 's/.*"([0-9]+):5000".*/\1/p' compose.override.yaml | head -n1)
# Point the host-side dev flow at the remapped Temporal gRPC port, overriding
# the fixed value from .env.local.
TEMPORAL_ADDRESS   := localhost:$(TEMPORAL_GRPC_PORT)
export TEMPORAL_ADDRESS
else
FRONTEND_PORT      := 3000
TEMPORAL_GRPC_PORT := 7233
TEMPORAL_UI_PORT   := 8233
BACKEND_PORT       := 8000
MOTO_PORT          := 4566
endif

# Banner listing where to reach the running components.
define show_urls
	@echo ""
	@echo "The stack is up. Open:"
	@echo "  Web UI             http://localhost:$(FRONTEND_PORT)"
	@echo "  Backend API        http://localhost:$(FRONTEND_PORT)/api"
	@echo "  Temporal dashboard http://localhost:$(TEMPORAL_UI_PORT)"
endef

##@ Infra

.PHONY: infra-up
infra-up: ## Bring up local infra (Moto, Temporal dev server, bucket/table init)
	docker-compose up -d temporal moto init

.PHONY: infra-down
infra-down: ## Stop infra containers (keeps containers and network around)
	docker-compose stop temporal moto init

.PHONY: infra-logs
infra-logs: ## Follow logs from infra containers
	docker-compose logs -f temporal moto

##@ App

.PHONY: backend
backend: ## Run the backend HTTP server with hot reload
	PORT=$(BACKEND_PORT) go tool air -c .air.backend.toml

.PHONY: worker
worker: ## Run the Temporal worker with hot reload
	go tool air -c .air.worker.toml

.PHONY: frontend
frontend: ## Run the Nuxt dev server with hot reload
	PORT=$(FRONTEND_PORT) \
	NUXT_DEV_API_TARGET=http://localhost:$(BACKEND_PORT)/api \
	NUXT_DEV_IMAGES_TARGET=http://localhost:$(MOTO_PORT)/aws-image-processing-demo-images-local \
	pnpm -C frontend dev

.PHONY: dev
dev: frontend/node_modules infra-up ## Start infra, then run backend + worker + frontend on the host with hot reload
	$(show_urls)
	@$(MAKE) -j backend worker frontend

frontend/node_modules: frontend/package.json
	pnpm -C frontend install

##@ Stack

.PHONY: app-up
app-up: ## Bring up the full stack in Docker (infra + worker + backend + frontend)
	docker-compose up -d
	$(show_urls)

.PHONY: app-down
app-down: ## Tear down the full stack (removes containers and network)
	docker-compose down

.PHONY: app-logs
app-logs: ## Follow logs from every stack container
	docker-compose logs -f

##@ Quality

.PHONY: test
test: ## Run Go unit tests
	go test ./...

.PHONY: check
check: test ## Run unit tests and static checks across modules
	go vet ./...
	pnpm -C frontend lint

##@ Build

.PHONY: worker-lambda-zip
worker-lambda-zip: ## Build the worker Lambda deployment artifact (build/worker.zip)
	@mkdir -p build
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 \
	  go build \
	  -tags lambda.norpc \
	  -ldflags "-s -w -X main.buildID=$(shell git rev-parse --short HEAD)" \
	  -o build/bootstrap ./cmd/worker
	cd build && rm -f worker.zip && zip worker.zip bootstrap

##@ Deploy

.PHONY: deploy
deploy: ## Provision AWS infra and deploy the frontend (uses .env)
	./scripts/deploy.sh

.PHONY: frontend-deploy
frontend-deploy: ## Rebuild and sync the frontend (uses .env)
	./scripts/frontend-deploy.sh

.PHONY: teardown
teardown: ## Destroy all AWS infrastructure (uses .env)
	./scripts/teardown.sh

##@ Worktree

.PHONY: worktree-ports
worktree-ports: ## Remap host ports off CASPER_PORT so parallel Casper workspaces don't collide
	@if [ -n "$$CASPER_PORT" ] && [ -f compose.yaml ]; then \
		base="$$CASPER_PORT"; \
		{ \
		  echo "# Generated by \`make worktree-ports\` for Casper workspace (CASPER_PORT=$$base)."; \
		  echo "# Remaps host-published ports off CASPER_PORT so parallel workspaces don't"; \
		  echo "# collide. Internal service-to-service ports are unchanged. Gitignored and"; \
		  echo "# regenerated per workspace — do not edit by hand."; \
		  echo "services:"; \
		  echo "  frontend:"; \
		  echo "    ports: !override"; \
		  echo "      - \"$$base:3000\""; \
		  echo "  temporal:"; \
		  echo "    ports: !override"; \
		  echo "      - \"$$((base + 1)):7233\""; \
		  echo "      - \"$$((base + 2)):8233\""; \
		  echo "  backend:"; \
		  echo "    ports: !override"; \
		  echo "      - \"$$((base + 3)):8000\""; \
		  echo "  moto:"; \
		  echo "    ports: !override"; \
		  echo "      - \"$$((base + 4)):5000\""; \
		} > compose.override.yaml; \
		echo "[worktree-ports] wrote compose.override.yaml (webui=$$base, temporal grpc=$$((base + 1)), temporal ui=$$((base + 2)), backend=$$((base + 3)), moto=$$((base + 4)))"; \
	else \
		echo "[worktree-ports] CASPER_PORT unset or compose.yaml missing; skipping"; \
	fi

##@ Helpers

.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make \033[36m<target>\033[0m\n"} \
		/^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } \
		/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(firstword $(MAKEFILE_LIST))
